#NOM    : Makefile
#OBJET  : lecture du superbloc d'une partition de type ext4
#HOWTO	: make; make clean
#AUTEUR	: Costil Iuiana 03/2023


LectSuperBlock : LectSuperBlock.c
	gcc -std=c99 -Wall LectSuperBlock.c -o LectSuperBlock -O0 -lm

clean:
	rm -f *~ LectSuperBlock sb
