#!/bin/bash
#NOM    : Demo
#CLASSE : ED - LaboED 02-02
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
clear
C='\033[44m'
E='\033[32m\033[1m'
W='\033[31m\033[1m'
N='\033[0m'
echo "Démonstration du programme FichierCreux"
echo "---------------------------------------"
echo
echo -e "Éxecution de ${E}./FichierCreux${N} :"
./FichierCreux
echo ----------------------------------
echo "Le programme FichCreux.dat a crée un fichier FichCreux.dat"
echo -e "qui contient ${E}Hello world${N} au début et" 
echo -e "${E}Bye world${N} en position 100000"
echo
echo -n "Ce fichier a une taille de "
ls -l FichCreux.dat | awk '{print $5,"bytes"}'
echo -n 'et occupe sur le disque '
du -h FichCreux.dat | awk '{print $1}'
echo
echo -n "la taille d'un bloc sur le disque est de "
echo a > f.tmp; du -h f.tmp | awk '{print $1}'; rm -f f.tmp
echo
echo -n "Les extents"
echo	
filefrag -v FichCreux.dat
echo ----------------------------------
rm -f FichCreux.dat
echo "Le fichier FichCreux.dat est maintenant effacé pour éviter "
echo "de le copier sur un usb formaté en FAT"
echo "ou de l'ouvrir avec un traitement de texte"
echo -e "${C}             --> Enter pour continuer${N}"
read
