all: FichierCreux StatBlocks
FichierCreux: FichierCreux.c
	gcc -std=c99 -Wall FichierCreux.c -o FichierCreux
StatBlocks: StatBlocks.c
	gcc -std=c99 -Wall StatBlocks.c -o StatBlocks

clean:
	rm -f FichierCreux FichCreux.dat *~
